### ISSUE TITLE
Remote database

### ISSUE THREAD

**Issue by phainv** [centminmod/centminmod#101]
Hi all,

i have Server Mariadb => `Server 1`

Server 2: Using apache => Remote database `Server 1` => Working
Server 3: Using Nginx (centminmod) => Remote database `Server 1` => `Not working`

server 2 and server3 using same user and database. but server 3 returned `Connection refused`

I've tried localhost. This connected to `Server 1`
Thanks!

**Comment by centminmod** [comment]
Centmin Mod installs CSF Firewall https://centminmod.com/csf_firewall.html so you need to whitelist your remote database server on Centmin Mod server as per Getting Started Guide Step 4 https://centminmod.com/getstarted.html#4

**Comment by phainv** [comment]
Very thanks. it worked for me 👍 

```ssh
csf -a IP of Server 1
```
