### ISSUE TITLE
[Suggestion] Remove option 19) Install FFMPEG and FFMPEG PHP Extension

### ISSUE THREAD

**Issue by snowboarder04** [centminmod/centminmod#103]
As noted in the Centminmod [third-party YUM documentation ](https://centminmod.com/yum.html), it seems as though the ATrpms repository has been offline since 2015 and shows no sign of coming back.

Since this FFMPEG/PHP option explicitly requires ATrpms repository to be installed, configured and available, it seems counter intuitive to keep this option in place.

**Comment by centminmod** [comment]
Yes currently centmin mod is using a fall back mirror of ATrpms yum repo IIRC just for folks who still require it.
