### ISSUE TITLE
Trying to install

### ISSUE THREAD

**Issue by agreements** [centminmod/centminmod#104]
And i get the following.
installer.sh: line 175: bc: command not found
installer.sh: line 177: bc: command not found
installer.sh: line 180: /root/centminlogs/firstyum_installtime_241217-112815.log                                                                                           : No such file or directory
---------------------------------------------------------------------------
installer.sh: line 182: /root/centminlogs/firstyum_installtime_241217-112815.log                                                                                           : No such file or directory
tail: cannot open '/root/centminlogs/firstyum_installtime_*.log' for reading: No                                                                                            such file or directory
tail: cannot open '/root/centminlogs/centminmod_yumtimes_*.log' for reading: No                                                                                            such file or directory
tail: cannot open '/root/centminlogs/centminmod_downloadtimes_*.log' for reading                                                                                           : No such file or directory
tail: cannot open '/root/centminlogs/centminmod_ngxinstalltime_*.log' for readin                                                                                           g: No such file or directory
tail: cannot open '/root/centminlogs/centminmod_phpinstalltime_*.log' for readin                                                                                           g: No such file or directory
tail: cannot open '/root/centminlogs/*_install.log' for reading: No such file or                                                                                            directory
awk: fatal: cannot open file `/root/centminlogs/firstyum_installtime_*.log' for                                                                                            reading (No such file or directory)
awk: fatal: cannot open file `/root/centminlogs/*_install.log' for reading (No s                                                                                           uch file or directory)
installer.sh: line 196: bc: command not found
installer.sh: line 198: bc: command not found
Total YUM + Source Download Time: 0.0000
Total Nginx First Time Install Time: 0.0000
Total PHP First Time Install Time: 0.0000
Download Zip From Github Time: 0.0000
Total Time Other eg. source compiles: 0.0000
Total Centmin Mod Install Time: 0.0000
---------------------------------------------------------------------------
Total Install Time (curl yum + cm install + zip download): 0.0000 seconds
---------------------------------------------------------------------------

**Comment by centminmod** [comment]
what was exact command used ? as outlined at https://github.com/centminmod/centminmod ?

you're missing bc package so might need to start with 

```
yum -y install git wget nano bc unzip
```
