### ISSUE TITLE
shebang should be bash not sh

### ISSUE THREAD

**Issue by aqw** [centminmod/centminmod#105]
I saw you link this script on Hackernews. Just thought I'd mention that your shebang is declared as ``/bin/sh`` but your script uses features (such as [[ ]]) that are in bash.

Running this script on systems which point sh to a more minimal shell (such as dash, mksh, etc) will fail.

---Alex

EDIT: just realized there's a lot more code in this repo. The file linked was centmin.sh

**Comment by centminmod** [comment]
Hi @aqw pretty sure all my scripts use `/bin/bash` not `/bin/sh` ? Centmin Mod is built for CentOS 6 & 7 systems fresh virgin systems only so usually they'd default to using bash.

**Comment by centminmod** [comment]
oh wait your right LOL centmin.sh is using `/bin/sh` could of sworn it was `/bin/bash` whoops !
