### ISSUE TITLE
[[ -z cat file ]] -> [ -s file ]

### ISSUE THREAD

**Issue by aqw** [centminmod/centminmod#106]
https://github.com/centminmod/centminmod/blob/a2265f818866cea065c2b233b4076cd317c92445/centmin.sh#L69

Can be replaced with

    if [ -s /etc/resolv.conf ]; then 

It will save you from spawning an unnecessary subshell.

I hope you don't mind the random nitpicks. I'm distracting myself as lunch approaches...

---Alex

**Comment by centminmod** [comment]
@aqw cheers I welcome feedback like this. Centmin Mod code is an evolution in my experience with shell scripting from noob 6+ yrs ago till now so you will see varying levels of proficiency with the code heh.

Coincidentally, another Alex @alexgoussev had a field day with feedback on my code ages back too https://github.com/centminmod/centminmod/pulls?q=is%3Apr+author%3Aalexgoussev :)

**Comment by aqw** [comment]
Oops. Yeah, I meant [ ! -s filename ]. My bad.

Thanks for the correction. :-)

---Alex
