### ISSUE TITLE
Installer stalls

### ISSUE THREAD

**Issue by makeshyft-tom-g** [centminmod/centminmod#109]
Hi, my installer for this stops at:

update varnish cache 4.1 yum repo config
Loaded plugins: fastestmirror, priorities, versionlock
http://apt.sw.be/redhat/el7/en/x86_64/rpmforge/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: apt.sw.be; Name or service not known"
Trying other mirror.
Retrieving key from https://packagecloud.io/varnishcache/varnish41/gpgkey
Importing GPG key 0xCBF5C49E:
 Userid     : "https://packagecloud.io/varnishcache/varnish41 (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: 9c96 f9ca 0dc3 f4ea 78ff 3328 34bf 6e8e cbf5 c49e
 From       : https://packagecloud.io/varnishcache/varnish41/gpgkey

Literally the stdout stops at this line

I'm on Digital Ocean CentOS 7.4 64x

Can anyone help?  I wanted to install the beta to test and use the  lets encrypt scripts in the vhost routines

**Comment by centminmod** [comment]
Just updated Centmin Mod 123.09beta01 with a fix so try a fresh install on fresh CentOS 7 reloaded image. Problem seems to be that DigitalOcean is having connectivity issues with packagecloud.io Varnish Cache yum repo so I have disabled it completely for now https://github.com/centminmod/centminmod/commit/582946edae29f07a6e55f0fa93365aebe93fa242
