### ISSUE TITLE
Back-to-back runs of option 22 produce cursor bug

### ISSUE THREAD

**Issue by makeshyft-tom-g** [centminmod/centminmod#110]
So today I ran option 22 ... 4 times and transferred 4 sites to a single droplet.

I noticed one additional bug which I think you will be able to reproduce.

When I finished one "option 22" run...... and then ran it again ..... after the first completed....... the cursor to type in the web addresses or emails was jumping to the beginning of the line and overwriting the labels / instructions.

When I did one, logged out, logged back in, that did not happen.

Thank you for the great platform... besides the error above and the connectivity error yesterday, it all worked beautifully.

**Comment by jjcav84** [comment]
That sounds more like an issue with the terminal or the droplet itself.  I have never heard of a script having that impact before, but let's see what George says.  Maybe post on the forums, and see if someone else has any other ideas.  What terminal are you using?  And are you using bash or something else like zsh?  I know when I used to use zsh with oh-my-zsh it had a little bit of latency at times.

**Comment by makeshyft-tom-g** [comment]
I'm using putty on Windows 7.  It is entirely possible you are right, I really wouldn't know if a script can cause that or not. Lets see.
