### ISSUE TITLE
Disabled "mysql service" keeps the service running after installation

### ISSUE THREAD

**Issue by oscarsmx** [centminmod/centminmod#111]
So, this is happening right now.

If you change "mysqlservice_disabled" in centmin.sh after installation the service is running.

**Comment by centminmod** [comment]
`MYSQLSERVICE_DISABLED='n'` needs to be set to `MYSQLSERVICE_DISABLED='y'` before Centmin Mod initial install. 

Instead of editing centmin.sh, proper way to override variables is to set them up in /etc/centminmod/custom_config.inc persistent config file prior to installation which means creating directory and file prior to initial install. This is outlined at https://centminmod.com/upgrade.html#persistent

You can see some examples of this in action in official linode stack script https://www.linode.com/stackscripts/view/152674. So before install 

```
mkdir -p /etc/centminmod
touch /etc/centminmod/custom_config.inc
echo "MYSQLSERVICE_DISABLED='y'" >> /etc/centminmod/custom_config.inc
yum -y update; curl -O https://centminmod.com/betainstaller.sh && chmod 0700 betainstaller.sh && bash betainstaller.sh
```

**Comment by oscarsmx** [comment]
I did change MYSQLSERVICE_DISABLED='n' to MYSQLSERVICE_DISABLED='y' before the installation

It's kind of weird since I did change pure-ftpd too and pure-ftpd was disabled.

This was done with the github clone of the current centminmod (I don't like the betainstaller)

**Comment by centminmod** [comment]
Git clone of the master branch or 123.08stable branch or 123.09beta01 branch ? Currently main active dev branch is 123.09beta01 with latest advancements which are literally years beyond 123.08stable. Once a week 123.09beta01 changes are merged into master branch. So if you cloned on github master you would be getting 123.09beta01 code which is ~1 week behind 123.09beta01 latest code.

But are you using CentOS 6 or CentOS 7, i think i might have found a bug in CentOS 6 routine for MYSQLSERVICE_DISABLED='y'

**Comment by oscarsmx** [comment]
123.08stable branch with centos 7.4

**Comment by centminmod** [comment]
Ok found a few problems that needed fixing when it comes to MYSQLSERVICE_DISABLED='y' routines. I've updated both 123.08stable and 123.09beta01 branches and master with the fix so if you do a fresh Centmin Mod install it should work. 

at end of initial install should see

```
--------------------------------------------------------
Stopping mysql service:
service mysql stop
Stopping mysql (via systemctl):  [  OK  ]
Disabling mysql service:
chkconfig mysql off
Note: Forwarding request to 'systemctl disable mysql.service'.
Removed symlink /etc/systemd/system/multi-user.target.wants/mariadb.service.
Removed symlink /etc/systemd/system/mysqld.service.
Removed symlink /etc/systemd/system/mysql.service.
--------------------------------------------------------
In future to re-enable mysql service type these 2 commands:
service mysql start
chkconfig mysql on
--------------------------------------------------------
```

Let me know if it's fixed for you.

**Comment by oscarsmx** [comment]
Working again, thank you!
