### ISSUE TITLE
MongoDB and Redis error after installation php 7.0

### ISSUE THREAD

**Issue by oscarsmx** [centminmod/centminmod#112]
This is the error:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/mongo.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/mongo.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/redis.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/redis.so: cannot open shared object file: No such file or directory in Unknown on line 0

Mongo downloaded (after upgrading the version editing the version number over centmin.sh) fine but this bug keep happening. About redis, well it just happen to follow the config so I don't know about it.

**Comment by centminmod** [comment]
Which version of Centmin Mod 123.08stable or 123.09beta01 ? As to solution see https://community.centminmod.com/threads/php-warning-php-startup-unable-to-load-dynamic-library.9113/

**Comment by oscarsmx** [comment]
Centmin Mod 123.08stable 

I did change (centmin.sh) phpmongodb=y and updated the # to 1.4.3

PHPMONGODB='y'
MONGODBPHP_VER='1.4.3'

As fix I been doind pcel install mongodb and just change the mongodb.ini to the right setting.

**Comment by centminmod** [comment]
Ah now I remember 123.08stable uses the only mongo php extension https://pecl.php.net/package/mongo so setting version to 1.4.3 won't work. Only 123.09beta01 with newer code uses newer mongodb php extension https://pecl.php.net/package/mongodb so technically not a bug. As 123.09beta01 gets all the newer stuff :)

**Comment by centminmod** [comment]
Backported 123.09beta01's mongodb routine for 123.08stable https://github.com/centminmod/centminmod/commit/f14e3a567370bb5d31bc790d8db661e6531f8804 so you can update existing 123.08stable install via centmin.sh menu option 23 submenu option 2 (would need to do submenu option 1 first to switch 123.08stable to git repo based /usr/local/src/centminmod first)
