### ISSUE TITLE
Add by default automatic "IF" http redirect to Nginx server block

### ISSUE THREAD

**Issue by lutechi** [centminmod/centminmod#113]
Hello,

I recently switched from easyengine and I am loving Centmin Mod. Great work!

It was bugging me that I was able to access a WordPress vhost domain via "www" and "non-www". The site I created with option 22 it only created the SSL.conf.

These were some of my options on Centmin Mod Menu 123.09beta01:

Menu - 22
domainname.com 
Lets Encrypt enabled
Redis Cache

The target goal was to make sure everything would redirect to "https://domain.com".

I was able to solve it by reading this page after digging through the forums:
[https://centminmod.com/nginx_domain_dns_setup.html#httpsredirect](https://centminmod.com/nginx_domain_dns_setup.html#httpsredirect)

**To non-www https:**
`server {
  listen 443 ssl http2;
  server_name newdomain.com www.newdomain.com;

   ##  redirect https www to https non-www
      if ($host = 'www.newdomain.com' ) {
         return 302 https://newdomain.com$request_uri;
      }`

Is it possible to add it by default on future updates or ask a question in the creation of the site if **"www/non-www"** will not be used so we don't have to do this manually?

It is not a big of a deal if is a must to do manually since I see there are several options on that page for different cases, but I rather have everything pointing to the right domain from scratch by default. I think I was just lucky that I found how to fix it in a few minutes searching, but others might not be as lucky.

Thanks again for developing this.

**Comment by jjcav84** [comment]
You should use a CNAME record in the DNS settings with your registrar to
take care of the www sub domain.

**Comment by lutechi** [comment]
I used an "A" record instead of "CNAME" after reading that supposedly is faster because of less lookups.

Is it maybe that's the cause of having available www and non-www and I had to use the "if" block to make it permanent?

Thanks for your suggestion.

**Comment by jcatello** [comment]
I wouldn't recommend using 'if' regardless:

https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/

instead use seperate server blocks, example:

non https will redirect both www and now www to https://domain.com

```
  server {
            listen   80;
            server_name domain.com www.domain.com;
            return 301 https://domain.com$request_uri;
       }

```
then for https to force non www:

```
server {
  listen 443 ssl http2;
  server_name www.domain.com;

  #ssl_dhparam /usr/local/nginx/conf/ssl/domain.com/dhparam.pem;
  ssl_certificate      /usr/local/nginx/conf/ssl/domain.com/domain.com.crt;
  ssl_certificate_key  /usr/local/nginx/conf/ssl/domain.com/domain.com.key;
  include /usr/local/nginx/conf/ssl_include.conf;

  return 301 https://domain.com$request_uri;
  }
```

**Comment by jjcav84** [comment]
You need both an A record for the IP address and a CNAME record for sub
domains such as www

**Comment by lutechi** [comment]
Thanks @jcatello, I changed it to 3 blocks as you have suggested.

**Comment by lutechi** [comment]
Hi @jjcav84,

I do have 2 "A" records pointing to the VPS, 1 for @ and 1 for www, otherwise Letsencrypt would have failed if I didn't.

**Comment by jcatello** [comment]
A CNAME record shouldn't be relied on to do any kind of a redirect

**Comment by jjcav84** [comment]
That’s how I setup my dns records. Others do it differently and people do
debate dns configuration but I’m definitely not alone on this.

https://serverfault.com/questions/181927/should-cname-be-used-for-subdomains?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by centminmod** [comment]
yeah technicaly @jcatello stated way is best https://github.com/centminmod/centminmod/issues/113#issuecomment-395885913

though it's easier for noobs to do a if redirect. I  should update my guide eventually :)

**Comment by jcatello** [comment]
> That’s how I setup my dns records. Others do it differently and people do
> debate dns configuration but I’m definitely not alone on this.
> 
> https://serverfault.com/questions/181927/should-cname-be-used-for-subdomains?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

That's completely different though, you are referencing it to be used as a redirect which a CNAME record just simply is not.  In fact if you read the accepted answer on serverfault, you'll see some good pros and cons and in my eyes the pros outway the crons because a CNAME can actually degrade the performance, although very small, in this day and age speed is everything.

**Comment by jjcav84** [comment]
Ok here's how I really do it for WordPress servers.  I was caught up in the middle of my associate fubaring a docker swarm deployment so I gave a really simple answer that works.

 server {

   server_name example.com. www.example.com;
   return 301 https://example.com$request_uri;
   include /usr/local/nginx/conf/staticfiles.conf;
 }

server {
  listen 443 ssl http2;
  server_name example.com www.example.com;

  include /usr/local/nginx/conf/ssl/example.com/example.com.crt.key.conf;
  include /usr/local/nginx/conf/ssl_include.conf;

  rewrite ^/wp-content/uploads/edd/(.*)\.zip$ / permanent;
  http2_max_field_size 16k;
  http2_max_header_size 32k;
  ssl_ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS;
  ssl_prefer_server_ciphers   on;

  ssl_buffer_size 1369;
  ssl_session_tickets on;

  # enable ocsp stapling
  resolver 8.8.8.8 8.8.4.4 valid=10m;
  resolver_timeout 10s;
  ssl_stapling on;
  ssl_stapling_verify on;

  # ngx_pagespeed & ngx_pagespeed handler
  include /usr/local/nginx/conf/pagespeed.conf;
  include /usr/local/nginx/conf/pagespeedhandler.conf;
  include /usr/local/nginx/conf/pagespeedstatslog.conf;

  access_log /home/nginx/domains/example.com/log/access.log combined buffer=256k flush=5m;
  error_log /home/nginx/domains/example.com/log/error.log;

  include /usr/local/nginx/conf/autoprotect/example.com/autoprotect-example.com.conf;
  root /home/nginx/domains/example.com/public;
  include /usr/local/nginx/conf/503include-main.conf;

  include /usr/local/nginx/conf/wpincludes/example.com/wpsupercache_example.com.conf;

  location / {
  include /usr/local/nginx/conf/503include-only.conf;
  try_files /wp-content/cache/supercache/$http_host/$cache_uri/index.html $uri $uri/ /index.php?q=$uri&$args;

  }

location ~* /(wp-login\.php) {
    limit_req zone=xwplogin burst=1 nodelay;
    auth_basic "Private";
    include /usr/local/nginx/conf/php-wpsc.conf;

}

location ~* /(xmlrpc\.php) {
    limit_req zone=xwprpc burst=45 nodelay;
    include /usr/local/nginx/conf/php-wpsc.conf;

}

location ~* /wp-admin/(load-scripts\.php) {
    limit_req zone=xwprpc burst=5 nodelay;
    include /usr/local/nginx/conf/php-wpsc.conf;
}

location ~* /wp-admin/(load-styles\.php) {
    limit_req zone=xwprpc burst=5 nodelay;
    include /usr/local/nginx/conf/php-wpsc.conf;
}

  include /usr/local/nginx/conf/wpincludes/example.com/wpsecure_example.com.conf;
  include /usr/local/nginx/conf/php-wpsc.conf;

  include /usr/local/nginx/conf/pre-staticfiles-local-example.com.conf;
  include /usr/local/nginx/conf/pre-staticfiles-global.conf;
  include /usr/local/nginx/conf/staticfiles.conf;
  include /usr/local/nginx/conf/drop.conf;
  include /usr/local/nginx/conf/vts_server.conf;
}

that's basically what option 22 does when you use letsencrypt and redirect with server blocks i never have to write any extra configuration and if redirects shouldn't be necessary

**Comment by jjcav84** [comment]
you're definitely right but he used option 22 which is a WordPress installation and it if you type in www.example.com it redirects to example.com because as you said PHP does it.  So I don't understand what the problem was.

**Comment by jcatello** [comment]
Most likely the theme, I've seen it do similar things like breaking WP from adding the trailing / at the end of page/post URL's.

**Comment by lutechi** [comment]
Thanks guys for all the help and knowledge this noob (me) gained from suggesting a default change :)

This was with the default theme from WordPress install as I am testing before I add any plugins or themes.

I was just trying to minify steps for future installs if it was possible. I appreciate the time and info provided which it was definitely useful.

**Comment by jjcav84** [comment]
Any problems you have definitely check out community.centminmod.com and get on the forum.  George and the other guys on there are really good and so helpful.  I honestly don't know how he has the time to do all of this and troubleshoot user's issues as well but he does a tremendous job.
