### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by ponasromas** [centminmod/centminmod#115]
Currently using this mod and it is fantastic. Have a few suggestions:

- Domain remove: easy and fast way to delete all info about domain (vhost, ftp etc.)
- PerconaDB support
- Multi-PHP support (configurable per vhost)
- Rudimentary mail support (create / delete mailbox)

**Comment by centminmod** [comment]
Hi thanks for suggestions

* Improved menu options, Percona MySQL and multi PHP-FPM version support is on the to-do list dev roadmap at https://github.com/centminmod/centminmod/projects/1
* Unfortunately, mail @ yourdomain.com isn't on the books right now as outlined at https://community.centminmod.com/threads/email-server-on-centminmod.6435/

**Comment by Octolus** [comment]
Domain remove +1
Multi-PHP Support +1

**Comment by centminmod** [comment]
multiple PHP-FPM pools has been supported optionally since 123.08stable and refined in 123.09beta01 https://community.centminmod.com/threads/centmin-mod-08-beta03-multiple-php-fpm-pools-support-added.3672/

**Comment by oscarsmx** [comment]
I did a simple script to delete domains:

https://github.com/oscarsmx/Simple-Centminmod-Domain-Removal

It's simple so it will only delete the folder at domains, nginx conf and ssl.

However it doesn't delete virtual ftp users I'll think about that later but as you can type anything you need to remember the user you use for that site.

**Comment by centminmod** [comment]
thanks @oscarsmx  for sharing :)

FYI, For latest beta (123.09beta01), You also get a log file for each Nginx vhost created which also lists the commands in 123.09beta01 and higher example for http2.domain.com remove log at `/root/centminlogs/centminmod_011118-171959_nginx_addvhost_nv.log`

contents of `/root/centminlogs/centminmod_011118-171959_nginx_addvhost_nv.log` after nginx vhost creation would have something at end of log like

```
-------------------------------------------------------------
Commands to remove http2.domain.com

 pure-pw userdel cMpEOOo>0%tq;tO733{AT%
 rm -rf /usr/local/nginx/conf/conf.d/http2.domain.com.conf
 rm -rf /usr/local/nginx/conf/conf.d/http2.domain.com.ssl.conf
 rm -rf /usr/local/nginx/conf/ssl/http2.domain.com/http2.domain.com.crt
 rm -rf /usr/local/nginx/conf/ssl/http2.domain.com/http2.domain.com.key
 rm -rf /usr/local/nginx/conf/ssl/http2.domain.com/http2.domain.com.csr
 rm -rf /usr/local/nginx/conf/ssl/http2.domain.com
 rm -rf /home/nginx/domains/http2.domain.com
 rm -rf /root/.acme.sh/http2.domain.com
 rm -rf /root/.acme.sh/http2.domain.com_ecc
 rm -rf /usr/local/nginx/conf/pre-staticfiles-local-http2.domain.com.conf
 service nginx restart

-------------------------------------------------------------
vhost for http2.domain.com setup successfully
http2.domain.com setup info log saved at: 
/root/centminlogs/centminmod_011118-171959_nginx_addvhost_nv.log
-------------------------------------------------------------
```
