### ISSUE TITLE
Server Administrator Emails aren't saved/remembered

### ISSUE THREAD

**Issue by phillf** [centminmod/centminmod#118]
I am not sure why or if anyone else has run into this but at least for me the Server Administrator email is not being remembered. I set it and the menu takes it but upon exit and restart it asks for it again like I never even set it.

Centminmod Version:  Centmin Mod Menu 123.09beta01 centminmod.com
OS Version: centos-release-7-5.1804.5.el7.centos.x86_64
```
--------------------------------------------------------------------
Setup Server Administration Email
Emails will be used for future notification alert features
--------------------------------------------------------------------
Hit Enter To Skip...
Will be prompted everytime run centmin.sh if both emails not entered
--------------------------------------------------------------------
enter primary email: myeamail@somedomain.com
enter secondary email: 
--------------------------------------------------------------------
```

**Comment by centminmod** [comment]
Probably not clear but both primary and secondary email fields need to populated for it to be saved. So for secondary you can enter same email address as primary if you don't have a 2nd email. Will add clarification to that prompt :)
