### ISSUE TITLE
Be docker compatible with centos

### ISSUE THREAD

**Issue by williamdes** [centminmod/centminmod#135]
**Background Information**

Please fill in any relevant information that applies to you:

* **CentOS Version:** i.e. CentOS 7 64bit
* **Install Method:** From website `yum -y update; curl -O https://centminmod.com/installer.sh && chmod 0700 installer.sh && bash installer.sh`

**Describe the bug**
`installer.sh: line 182: bc: command not found`
`installer.sh: line 59: wget: command not found`

This errors can also be seen on the phpMyAdmin installer script

**Expected behavior**
Install without errors

**Additional context**
Run `docker run --rm -v /mnt/Dev:/mnt/Dev -it centos:centos7 bash` to start the process

**Comment by williamdes** [comment]
My SSD was full, sorry.

**Comment by centminmod** [comment]
Thanks for testing @williamdes - might want to try the 123.09beta01 installer that's what most folks actually use https://centminmod.com/install.html too :)
