### ISSUE TITLE
Support Centos 8 ?

### ISSUE THREAD

**Issue by imManhIT** [centminmod/centminmod#141]
centminmod will add support centos 8 ? 
Thank you.
 
https://github.com/centminmod/centminmod/projects/1#card-21199188

**Comment by centminmod** [comment]
CentOS 8 support is a work in progress due to lagging behind EPEL 8 and other yum packages being missing. You can follow/watch or subscribe to sticky thread at https://community.centminmod.com/threads/centmin-mod-centos-8-compatibility-worklog.18372/ as to the progress.

**Comment by kimmyfarm** [comment]
CentOS 8 will die soon, hope centminmod will support Unbuntu

**Comment by MobileCity120ThaiHa** [comment]
> CentOS 8 support is a work in progress due to lagging behind EPEL 8 and other yum packages being missing. You can follow/watch or subscribe to sticky thread at https://community.centminmod.com/threads/centmin-mod-centos-8-compatibility-worklog.18372/ as to the progress.

The last update was from April, are you still working to add support new OS ?

**Comment by centminmod** [comment]
Yes I am though it's delayed right now, you can follow the latest update at https://community.centminmod.com/threads/centmin-mod-centos-8-compatibility-worklog.18372/#post-90596
