### ISSUE TITLE
OPcache on shared hosting

### ISSUE THREAD

**Issue by tobias992** [centminmod/centminmod#147]
Hi,

i checked little bit your configs. At the moment i try to find a solution to use OPcache on shared hosting servers.
I saw that you also dont have a "good" solution for this.

php_admin_value[opcache.file_cache] = /home/websitea/html/opcache
php_admin_value[opcache.file_cache_only] = 1

I think that could be the solution. But i tested it... failure.

Next solution would be to use a own Master Process for each Website. Do you have other ideas or maybe do you work on a solution for this problem?

OPcache makes +300% performance and i dont want to disable it. On WooCommerce shops you really can feel the faster workflows.

**Comment by centminmod** [comment]
FAQ item 2 https://centminmod.com/faq.html. Centmin Mod isn't made for shared hosting as such. To isolate the Zend Opcache for each site will need PHP-FPM pool each with it's own master process. However, you will increase memory usage/allocation for each site you do this for. But separate PHP-FPM master configuration isn't supported out of box with Centmin Mod though you can do it yourself if had the know-how. For Centmin Mod it's best if you need to isolate a site, to have it on it's own VPS server separate from others.
