### ISSUE TITLE
From acme.sh v3.0.0, acme.sh is using Zerossl as default ca, instead of LetsEncrypt and this breaks the vhost add functionality with LetsEncrypt

### ISSUE THREAD

**Issue by rcbarriga** [centminmod/centminmod#148]
At the moment i tried to generate a new vhost setup with a LetsEncrypt issued live certificate but the end result was the self signed certificate, then i found the following after some debugging on the script:

Currently Centminmod is using an ACME Shell script: acme.sh (https://github.com/acmesh-official/acme.sh) for issuing the LetsEncrypt certificates, since Centminmod downloads the latest version of this script, which a few days ago was updated to version 3.0.0 and this got the following changes:

_[Starting from August-1st 2021, acme.sh will release v3.0, in which the default CA will use ZeroSSL instead.](https://github.com/acmesh-official/acme.sh/wiki/Change-default-CA-to-ZeroSSL)_

_[From acme.sh v3.0.0, acme.sh is using Zerossl as default ca, you must register the account first(one-time) before you can issue new certs.](https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA)_

_Will I still be able to use letsencrypt then?
Yes, of course. You are still free to use any supported CA with providing --server parameter._

_acme.sh  --issue  -d example.com --dns dns_cf    **--server  letsencrypt**_

At the moment i couldnt locate where in the script we should pass this parameter (--server  letsencrypt) to the script to keep it working as usual, because of that i'll open this bug issue, thank you.

**Comment by rcbarriga** [comment]
Already found the fix in the following [commit](https://github.com/centminmod/centminmod/commit/ed18071309ebf94982a7597e4445268fa13dc0af#diff-d180325d0d0c5ce0b31984d7f6a8f0e24e6b1e15d6bb056b709dd430cd2b0a49)

And the fix is stated on commit description:

_- you can also manually force this update via a one time task by running cmupdate command on Centmin Mod 123.09beta01 or higher installs and then manually run acme.sh client update via command:

**/usr/local/src/centminmod/addons/acmetool.sh acmeupdate**_

**Comment by centminmod** [comment]
Thanks, I added more fixes for this too at https://community.centminmod.com/threads/acmetool-sh-1-0-74.21600/ with commit at https://github.com/centminmod/centminmod/commit/d8963fa87dee2e8066bfa6107753f588941dbd0a

**Comment by rcbarriga** [comment]
Thank you, that should be enough
