### ISSUE TITLE
Dual-core CPU cannot open php PGO extension

### ISSUE THREAD

**Issue by ocdevcn** [centminmod/centminmod#153]
1、I used the command to check that my CPU is dual-core
grep -c "processor" /proc/cpuinfo
picture:：https://prnt.sc/1okhs2c
2、I am in /etc/centminmod/custom_config.inc and fill in the following:
PHP_PGO='y'
PHP_PGO_ALWAYS='y'
3、Centminmod Version：
1.2.3-eva2000.09 beta install

I use Bandwagon host，
No matter what I do, I will never get php pgo

**Comment by ocdevcn** [comment]
Log:  https://gist.github.com/ocdevcn/8c1b7672409ca41560258fcfff124237

**Comment by Eckybrazzz** [comment]
What is the output of 
```
lscpu
```
