### ISSUE TITLE
How to strip tracking parameters via nginx?

### ISSUE THREAD

**Issue by erikdemarco** [centminmod/centminmod#154]
Currently centminmod depends on cache-enabler to remove tracking parameters such as utm_source,gclid,fbclid,etc.

Is there any way to remove this only via nginx config? So we dont need to install cache enabler?

**Comment by centminmod** [comment]
Probably best to ask on official Centmin Mod community forums at https://community.centminmod.com/. You can do it via nginx or more efficiently if you use Cloudflare with Cloudflare Transform rules to rewrite URL and their query string arguments https://developers.cloudflare.com/rules/transform. Examples at https://developers.cloudflare.com/rules/transform/url-rewrite/examples
