### ISSUE TITLE
installer broken it doesn't install everything

### ISSUE THREAD

**Issue by oscarsmx** [centminmod/centminmod#155]
fresh centos7 with stable and beta installer don't install pass nginx

tried at OVH vps and Linode same results.

MariaDB 10.x Repo setup...

rpm --import http://yum.mariadb.org/RPM-GPG-KEY-MariaDB

Check for existing mariadb packages

Check for existing mariadb-libs package
rpm -e --nodeps mariadb-libs-5.5.68-1.el7.x86_64
warning: file /etc/my.cnf: remove failed: No such file or directory

MariaDB 5.5 YUM install...
time yum -q -y --disableplugin=fastestmirror,downloadonly --disablerepo=epel,rpmforge install perl-DBI
http://yum.mariadb.org/10.0/centos7-amd64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article

[[1;32;40m* Installing PHP
^[[m^O*************************************************
Forcing buildconf
Removing configure caches
buildconf: checking installation...
buildconf: autoconf version 2.69 (ok)
http://yum.mariadb.org/10.0/centos7-amd64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article

**Comment by centminmod** [comment]
Yes, the stable version has broken MariaDB 10.0 repo as it's EOL. For now the 123.09beta01 is the best option as it's most up to date and has PHP 7.1+ and PHP 8.0+ and 8.1+ support which stable version doesn't. See https://centminmod.com/install.html

**Comment by oscarsmx** [comment]
Tried the beta installer (default one) with the same results...

**Comment by centminmod** [comment]
That's strange as beta version doesn't use MariaDB 10.0 but uses 10.3. Are you registered on official Centmin Mod community forums at https://community.centminmod.com/ ? If so you can post in forums at https://community.centminmod.com/forums/install-upgrades-or-pre-install-questions.8/ and provide the initial install log for troubleshooting as outlined at https://community.centminmod.com/threads/how-to-troubleshoot-centmin-mod-initial-install-issues.102/

**Comment by centminmod** [comment]
Also which of the install command lines did you use from https://centminmod.com/install.html ?

**Comment by oscarsmx** [comment]
Yep I'll post asap. Right now I'm testing with the github method however I did try default commands at github

yum -y update; curl -O https://centminmod.com/installer.sh && chmod 0700 installer.sh && bash installer.sh

yum -y update; curl -O https://centminmod.com/betainstaller.sh && chmod 0700 betainstaller.sh && bash betainstaller.sh

I also tried a custom_config.inc method at first then moved to default commands. I'll let you know how it goes.

**Comment by centminmod** [comment]
Ok thanks for the info, if you can provide the initial install logs https://community.centminmod.com/threads/how-to-troubleshoot-centmin-mod-initial-install-issues.102/ it would be helpful to troubleshoot.

**Comment by oscarsmx** [comment]
I gotta go out to grab something to eat but yeah, github method it's also broken asap I'll post the logs

**Comment by oscarsmx** [comment]
Logs:

https://drive.google.com/file/d/1kKXavQRwt4I2eHHWWP8XE6bVOPF9a0C3/view?usp=sharing

**Comment by oscarsmx** [comment]
It seems that everything start with rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm [found]
curl: (6) Could not resolve host: apt.sw.be; Unknown error
error: http://apt.sw.be/RPM-GPG-KEY.dag.txt: import read failed(2).

apt.sw.be it's dead.

**Comment by oscarsmx** [comment]
Weird indeed.

Now it's working the beta installer with linode. Lets try OVH. I'll update here.

**Comment by centminmod** [comment]
Could of been temp VPS specific issues on your end preventing some downloads happening.

FYI, I've just released 124.00stable which is based on 123.09beta01 so you can try that too https://community.centminmod.com/threads/centmin-mod-124-00stable-130-00beta01-releases.22673/

**Comment by oscarsmx** [comment]
> Could of been temp VPS specific issues on your end preventing some downloads happening.
> 
> FYI, I've just released 124.00stable which is based on 123.09beta01 so you can try that too https://community.centminmod.com/threads/centmin-mod-124-00stable-130-00beta01-releases.22673/

Yeah it was something temporary but with that I did at least 5 reinstalls.

I'll try today. The reason I used the stable 08 was because openbasedir was still disabled globally and in the stable this was enable by default
