### ISSUE TITLE
CSS / readability issue on "Quick Curl Installer"

### ISSUE THREAD

**Issue by grand-lotus-iroh** [centminmod/centminmod#157]
If you may, please visit: https://centminmod.com/install.html and you'll notice under the **Quick Curl Installer** area there are `<pre class="terminal">` blocks but it's not possible to read them unless you highlight text.

Perhaps head over to stackoverflow or another popular website where people share code to find out which colors best match.

![63f-8O5](https://user-images.githubusercontent.com/1291364/216102227-7d1e99de-c101-4d6c-9760-9c6a7f0d0d6c.gif)

p.s. - the page is rather huge, and i think it would be cool if headers were anchored to make it easily scrollable / shareable -- https://www.w3schools.com/html/html_links_bookmarks.asp

**Comment by centminmod** [comment]
Hi @grand-lotus-iroh seems I missed this issue! Strange, I'm not seeing this on my end. You still see the issue?

**Comment by grand-lotus-iroh** [comment]
All fixed now. 😂    **Must be Magic!**
