### ISSUE TITLE
Problem with WP-CLI after fresh installation

### ISSUE THREAD

**Issue by EdwardBlack** [centminmod/centminmod#159]
Prequisite:
Fresh Vultr high frequency server with CentOS 7 x64
Install via `yum -y update; curl -O https://centminmod.com/betainstaller81.sh && chmod 0700 betainstaller81.sh && bash betainstaller81.sh`

After installation, when I want to use option 22, I get the following:
```--------------------------------------------------------
Enter option [ 1 - 24 ] 22
--------------------------------------------------------
DEDI_LISTEN="listen   80;"
------------------------------------------------------------
Installing wpcli.sh
------------------------------------------------------------
installing...

Error: /usr/bin/wp not found !!! Downloading now......
2023-05-12 17:37:09 URL:https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar [6729511/6729511] -> "/usr/bin/wp" [1]
Download done.

Error: /root/wpcli/wp-completion.bash not found !!! Downloading now......
2023-05-12 17:37:09 URL:https://raw.githubusercontent.com/wp-cli/wp-cli/main/utils/wp-completion.bash [495/495] -> "/root/wpcli/wp-completion.bash" [1]
Download done.


/usr/bin/env: php: No such file or directory
-------------------------------------------------------------
install wp-cli https://github.com/eriktorsner/wp-checksum
/usr/bin/env: php: No such file or directory
/usr/bin/env: php: No such file or directory
-------------------------------------------------------------
install wp-cli https://github.com/markri/wp-sec
/usr/bin/env: php: No such file or directory
-------------------------------------------------------------
update wp-cli packages
/usr/bin/env: php: No such file or directory
-------------------------------------------------------------
wp-cli info
/usr/bin/env: php: No such file or directory
-------------------------------------------------------------

-------------------------------------------------------------
wp-cli install completed
Read http://wp-cli.org/ for full usage info

-------------------------------------------------------------
Please log out of SSH session and log back in
You can then call wp-cli via command: wp
i.e. wp --info --allow-root
-------------------------------------------------------------

-------------------------------------------------------------
Setup full Nginx vhost + Wordpress + WP Plugins
-------------------------------------------------------------
```

Needless to say, the WordPress installation doesn't work. I tried to wipe the server and install centmin again. Exactly the same outcome. (Next I try to use 124.00stable to see if that works. I will report on that)
EDIT1: Sorry, I don't manage to format the code in a better way :/

**Comment by centminmod** [comment]
It looks like PHP-FPM failed to initially install. You can investigate by digging into the initial install log outlined at https://community.centminmod.com/threads/how-to-troubleshoot-centmin-mod-initial-install-issues.102/

FYI, for formatting code you can wrap code in markdown code tags which start with 3 backticks before and after code

Does it work with PHP 8.0 default installers?

**Comment by EdwardBlack** [comment]
Ok, I now tried 124.00stable with
`yum -y update; curl -O https://centminmod.com/installer81.sh && chmod 0700 installer81.sh && bash installer81.sh`
There I get the error:
```
------------------------------------------------------------
Installing wpcli.sh
------------------------------------------------------------
installing...

Error: /usr/bin/wp not found !!! Downloading now......
2023-05-12 18:20:31 URL:https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar [6729511/6729511] -> "/usr/bin/wp" [1]
Download done.

Error: /root/wpcli/wp-completion.bash not found !!! Downloading now......
https://github.com/wp-cli/wp-cli/raw/master/utils/wp-completion.bash:
2023-05-12 18:20:31 ERROR 404: Not Found.
Error: /root/wpcli/wp-completion.bash download failed.
```
I tried to take a look into installer_120523-175627_minimal.log, but I'm far, far away from providing anything useful. Sorry ;/

Next step was to try to install Beta with PHP 8.0.
`yum -y update; curl -O https://centminmod.com/betainstaller80.sh && chmod 0700 betainstaller80.sh && bash betainstaller80.sh`
Again the same as initial report. `/usr/bin/env: php: No such file or directory`

**Comment by centminmod** [comment]
I updated Centmin Mod 124.00stable and 130.00beta01 with a possible fix for one PHP issue related to recent CentOS 7 systemd-devel and net-snmp-devel update dependencies for PHP https://github.com/centminmod/centminmod/commits/124.00stable. Might not be related to your system specifically, but try again.

**Comment by EdwardBlack** [comment]
I'm happy to report, that this fixed the issue!
(I tried 130.00beta01 with PHP 8.1)

**Comment by centminmod** [comment]
Thanks @EdwardBlack for confirmation of fix and bug reporting ❤️
