### ISSUE TITLE
Nginx GeoIP and Passenger detection on Centmin Mod Nginx upgrades

### ISSUE THREAD

**Issue by centminmod** [centminmod/centminmod#29]
With current .07 beta 21 release, if you have enabled in centmin.sh either option below and compiled Nginx with GeoIP and Phusion Passenger support originally and then upgrade to a new Centmin Mod release the new updated centmin.sh would not have either of the below 2 options enabled. You'd end up compiling Nginx without GeoIP and Phusion Passenger support and potentially break your site(s) functionality if it relies on Nginx GeoIP and/or Phusion Passenger support

```
NGINX_GEOIP=y 
NGINX_PASSENGER='y'
```
Going to have to add a detection routine in for Nginx upgrade menu option 4 which will check to see if existing Nginx web server has Nginx GeoIP and/or Phusion Passenger module for Nginx compiled in.

Ran into this bug on the Centmin Mod Community forum server https://community.centminmod.com as I had NGINX_GEOIP=y set.

Current forum Nginx configuration is

```
nginx -V
nginx version: nginx/1.7.2
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) 
TLS SNI support enabled
configure arguments: --with-cc-opt='-I/svr-setup/staticlibssl/include -I/usr/include' --with-ld-opt='-L/svr-setup/staticlibssl/lib -Wl,-rpath -lssl -lcrypto -ldl -lz' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-http_ssl_module --with-http_gzip_static_module --with-http_stub_status_module --with-http_sub_module --with-http_addition_module --with-http_image_filter_module --with-http_secure_link_module --with-http_flv_module --with-http_realip_module --with-http_geoip_module --with-openssl-opt=enable-tlsext --add-module=../ngx-fancyindex-ngx-fancyindex --add-module=../ngx_cache_purge-2.1 --add-module=../headers-more-nginx-module-0.25 --add-module=../nginx-accesskey-2.0.3 --add-module=../nginx-http-concat-master --with-http_dav_module --add-module=../nginx-dav-ext-module-0.0.3 --with-openssl=../openssl-1.0.1h --with-libatomic --with-pcre=../pcre-8.35 --with-pcre-jit --with-http_spdy_module --add-module=../ngx_pagespeed-release-1.8.31.3-beta
```

**Comment by jeffwidman** [comment]
If something's fixed, do you mind closing the issue? I check repo's open issues every so often to see the unfixed issues... Same with pull requests, just either merge them or close them once they're handled.

**Comment by centminmod** [comment]
well it's only partially fixed for GeoIP.. haven't got around to detection for Phusion Passenger heh
