### ISSUE TITLE
phpng 7.0 working with memcached, imagick apcu?

### ISSUE THREAD

**Issue by hwongcom** [centminmod/centminmod#34]
hi there, i've seen centmin working with php7.0 is that real? how to set it up to get it done?

can anyone provide the installation guide?

https://community.centminmod.com/threads/php-5-7-phpng-support-testing-for-centmin-mod-betas.892/#post-3956

**Comment by centminmod** [comment]
PHP 7 first alpha is coming soon https://community.centminmod.com/threads/php-5-7-phpng-support-testing-for-centmin-mod-betas.892/page-5#post-14643 :)
