### ISSUE TITLE
Nginx not responding to IPv4 when Listen directive updated to support IPv6

### ISSUE THREAD

**Issue by jeffwidman** [centminmod/centminmod#36]
I just tried editing my server block from `listen 80;` to `listen [::]:80;` and after saving and then restarting nginx, I went from a working Xenforo site to a Nginx 404 page. 

I just upgraded to Nginx 1.7.9 (I'm using the beta08). The server block is the default centminmod nginx vhost one:

        server {
        listen                  80;
        listen                  443 ssl;

        server_name             demodomain.com;

        # ngx_pagespeed & ngx_pagespeed handler

I reverted back to the old ip4 listen block, restarted nginx, and everything works properly. 

My ISP (comcast) doesn't offer IP6 for my internet connection right now, so I can't check to see if the domain is responding correctly on IP6.

**Comment by centminmod** [comment]
did you compile or recompile Nginx with IPv6 support - from http://centminmod.com/nginx.html

> Nginx is source compiled. Prior to Nginx install, if you want Nginx to have IPv6 support configured (will add --with-ipv6), edit centmin.sh and set variable at top of file to yes, NGINX_IPV='y' before running menu option #1. If you don't use ipv6 (ask web host if unsure), then no need to edit NGINX_IPV variable.

for existing installs same edit NGINX_IPV='y' and run centmin.sh option 4 to recompile Nginx

use http://ip6.nl/ to check if your site is IPv6 ready i.e. for sslspdy.com test site of mine http://ip6.nl/#!sslspdy.com

of course ensure your have domain DNS AAAA record set too

**Comment by jeffwidman** [comment]
Yes `nginx -V` shows `--with-ipv6`

I'm waiting to setup the DNS record until I know that Nginx is correctly configured to listen for inbound IPv6 DNS requests. I was planning to just test the server by using the IPv6 IP address, not the domain name, but even before I got that far I noticed that just adding this listen block is taking the site down... even though it shouldn't be affecting the IPv4 traffic at all...

**Comment by centminmod** [comment]
my ipv6 usage and experience is limited. This is what i have for sslspdy.com for SSL config

    server {
    listen 80;
    listen [2604:180:1::fd2c:e402]:80 default_server ipv6only=on;
      server_name sslspdy.com www.sslspdy.com;
       return 301 https://$server_name$request_uri;
    }
    
    server {
      listen 443 ssl spdy;
      listen [2604:180:1::fd2c:e402]:443 default_server ssl spdy ipv6only=on;
      server_name sslspdy.com www.sslspdy.com;

**Comment by jeffwidman** [comment]
To be clear, this bug isn't a big deal. I reported it simply because I suspect it might be a bug in centminmod's build of nginx with ipv6.

The server block I was using for IPv6:
      server {
    listen                  [::]:80;
    listen                  443 ssl;

    server_name             demodomain.com;

**Comment by jeffwidman** [comment]
Actually, it looks like this is the culprit: http://trac.nginx.org/nginx/ticket/345

Nginx now has a default of `ipv6only=on`, so `listen [::]:80;` is functionally the same as `listen [::]:80; ipv6only=on`

To enable listening on both ipv4 and ipv6, need to explicitly tell the listen block to also listen on ipv4 with `listen [::]:80; ipv6only=off`

**Comment by jeffwidman** [comment]
Hmm... just tested this, and `service nginx restart` fails whenever `ipv6only=off`is set. 

If I have two separate listen directives, it works:

    server {
        listen                  80;
        listen                  [::]:80;

Weird--this shouldn't be necessary according to the serverfault and nginx bug ticket. Not sure if the culprit is nginx or how nginx is built by centminmod, or something else...

**Comment by kiksilog** [comment]
This is what I used
```
listen [::]:80;
  listen   80;
```

**Comment by centminmod** [comment]
@kiksilog thanks for chiming in :) pretty much what I use too from my sslspdy.com example above :)

**Comment by jeffwidman** [comment]
BTW, I was working on something else and found the issue. Nginx has a quirk where "ipv6only" variable can only be manually specified once per port across ALL domains. So most likely it's manually specified in another file thus can't be specified in my vhosts. More details here: https://codinginthetrenches.com/2013/12/14/nginx-ipv6only-setting-gotcha/
