### ISSUE TITLE
FFMPEG/ FFMPEG-PHP install no longer works

### ISSUE THREAD

**Issue by Lakshanz** [centminmod/centminmod#44]
The inc/ffmpeginstall.inc script won't work anymore because atrpms repository is dead now. There's an outdated mirror available now on https://www.mirrorservice.org/sites/dl.atrpms.net/ .

**Comment by centminmod** [comment]
yeah unfortunately atrpm is dead https://community.centminmod.com/threads/unable-to-install-ffmpeg-php-extension.1519/page-3 

for some folks i.e. Xenforo users they can use FFMpeg static binaries https://community.centminmod.com/threads/xenforo-media-gallery-ffmpeg-binary.4419/ instead for now

**Comment by Lakshanz** [comment]
Yes, mirror works fine.

Run `vim /etc/yum.repos.d/atrpms.repo` and insert 

>[atrpms]
>name=Fedora Core $releasever - $basearch - ATrpms
>baseurl=https://www.mirrorservice.org/sites/dl.atrpms.net/el$releasever-$basearch/atrpms/stable
>gpgkey=http://ATrpms.net/RPM-GPG-KEY.atrpms
>enabled=1
>gpgcheck=0

Save & run ffmpeg install again.

**Comment by centminmod** [comment]
thanks @Lakshanz will look into it and see if the mirror can be trusted given atrpm history now

**Comment by centminmod** [comment]
@Lakshanz i updated centmin mod 123.09beta01 branch with the mirror for now https://community.centminmod.com/posts/21046/

**Comment by Lakshanz** [comment]
@centminmod Since ATrpms is not longer maintained and still offer older versions of FFMpeg, i think move nux-dextop repository (http://li.nux.ro/repos.html) would be great.
