### ISSUE TITLE
installer.sh - network resilient issue

### ISSUE THREAD

**Issue by Xon** [centminmod/centminmod#45]
The recommended unattended install process is not resilient to network errors.

```
curl -O https://centminmod.com/installer.sh && chmod 0700 installer.sh && bash installer.sh
```

The commands after the curl will execute even if the network connection is interrupted. This will result in the arbitrary scripting being executed, which can result in expected and unknowable behaviour.

The recommended workaround is to ensure **all** code in a function definition, and as the very last statement execute the function wrapping the code.

**Comment by centminmod** [comment]
> The recommended workaround is to ensure all code in a function definition, and as the very last statement execute the function wrapping the code.

thanks @Xon got an example ? fyi, the installer.sh is only 10kb in size

**Comment by Xon** [comment]
This is probably the best description: https://www.seancassidy.me/dont-pipe-to-your-shell.html

I'm not concerned about the security artefacts that people talk about with curl|bash, but ensuring the installer is reliable in the face of network interruptions.

**Comment by centminmod** [comment]
oh i see what you mean regarding the code inside installer.sh, i though you meant the command line itself

**Comment by Xon** [comment]
:+1:
