### ISSUE TITLE
Can you change your git settings to have git 'fast forward' when you merge?

### ISSUE THREAD

**Issue by jeffwidman** [centminmod/centminmod#49]
I always review the commit log before updating, and it's a bit inconvenient that the centminmod commit log is filled with all these unnecessary 'merged branch' commit messages. 

For some git workflows that would make sense, but I don't think that's true here because the only work you're doing is on the branch and then merging into master. 

By default, Git should fast-forward these merges so you don't get the additional 'merged' commit message, so you must have either globally changed this default or be using `--no-ff` in your merge commits. 

Would you mind stopping this just so there's a cleaner commit log? 

Here's more background on what's happening:
http://stackoverflow.com/questions/2500296/can-i-make-fast-forwarding-be-off-by-default-in-git
http://stackoverflow.com/questions/2850369/why-does-git-fast-forward-merges-by-default

I know your git foo isn't strong, but you really ought to spend a few hours reading this (totally free): http://git-scm.com/book/en/v2 It helped me tremendously on having a better understanding of how git works. I don't always remember the commands exactly, but now I understand generally what I'm trying to accomplish, so it's much easier to google for the specific syntax.

**Comment by centminmod** [comment]
I'll see what i can do, i only use Git GUI via sourcetree app on windows so it's probably a setting some where :)

**Comment by jeffwidman** [comment]
On *nix machines, there's a `.gitconfig` file that also sets things. Possibly you have one somewhere on Windows and don't realize it? 

Good suggestion to follow the stable branch, I'll do that. 

Also, I still suggest you checkout the git book if you get time ever, it helped me a lot.

**Comment by centminmod** [comment]
Cheers @jeffwidman i checked the .gitconfig and it isn't set so can't see why it behaves that way heh. Will check out the git book.. though I am most comfortable with the visual gui for Sourcetree especially when it highlights the diffs and changes I am about to commit :)

**Comment by jeffwidman** [comment]
I use Sourcetree most of the time myself as I find it more convenient than the command line. But I didn't really understand how the Git branching model worked until I read Chapter 3 of that book.

**Comment by centminmod** [comment]
Cheers @jeffwidman i've actually read that book :)

**Comment by centminmod** [comment]
whoops i almost wiped 123.08stable branch doing some tests for this LOL

also read at https://www.atlassian.com/git/tutorials/git-log/filtering-the-commit-history you can filer out merge commits from log viewing

> You can prevent git log from displaying these merge commits by passing the --no-merges flag:

    git log --no-merges
