### ISSUE TITLE
 postgresql php extension 

### ISSUE THREAD

**Issue by TooKennySupreme** [centminmod/centminmod#51]
Hello,

I can not install the corect php70w-pgsql. The only one I get is pdo_pgsql.

Can you tell me what I have to do to get the php7 working with pgsql

Best

**Comment by centminmod** [comment]
Hi @TooKennySupreme 

You might want to sign up on official forums https://community.centminmod.com for more insight and info. Centmin Mod doesn't use php yum packages but source compiles PHP and it's required php extensions see http://centminmod.com/phpfpm.html. 

As such for pdo_pgsql, it's currently a new addition to centmin mod 123.09beta01 only see https://community.centminmod.com/threads/centmin-mod-09-beta-branch-testing.4128/page-3#post-18578 and enabling variable POSTGRESQL=y via persistent config file at /etc/centminmod/custom_config.inc and you run centmin.sh menu option 5 to recompile PHP server, it will install PostgreSQL 9.4 server and devel yum packages from official PostgreSQL YUM repository at http://yum.postgresql.org/ if not already installed and then append to PHP-FPM configuration options the --with-pdo-pgsql=/usr/pgsql-9.4 configure option to enable and install pdo-pgsql PHP driver extension to allow PHP to communicate with PostgreSQL server.

**Comment by centminmod** [comment]
Just updated 123.09beta01 to support postgresql 9.5 server and php extension via same outlined method at https://community.centminmod.com/posts/23957/

**Comment by TooKennySupreme** [comment]
Hi, 

If we need an specific configuration is no way we can get the information from the community.
Ex: I need an  gnupg for php56 how do I install this ?

If we make an pay contribution do we get an FULL  documentation for centminmod...?

Best

**Comment by TooKennySupreme** [comment]
To give you an hint : 
with pdo-pgsql PHP you can not communicate with PosgreQSL you still need to
install:
php56w-pgsql	php-pdo_pgsql, php_database

Any way, you guys done an very good job .......!

Best

**Comment by centminmod** [comment]
most documentation is on official site http://centminmod.com/ + forums https://community.centminmod.com/ and anything else you have questions about should be asked on the forums if possible https://community.centminmod.com/ as it's best for me to answer a question once where every forum member can benefit from that same answer ;)

Centmin Mod doesn't use any php related yum packages at all, so installing them won't make a difference. Are those webstatic yum packages you're looking for https://webtatic.com/packages/php56/ ? As from that page, php56w-pgsql	package provides both php-pdo_pgsql, php_database and 

and php56w-pgsql provides

```
rpm -ql php56w-pgsql 
/etc/php-zts.d/pdo_pgsql.ini
/etc/php-zts.d/pgsql.ini
/etc/php.d/pdo_pgsql.ini
/etc/php.d/pgsql.ini
/usr/lib64/php-zts/modules/pdo_pgsql.so
/usr/lib64/php-zts/modules/pgsql.so
/usr/lib64/php/modules/pdo_pgsql.so
/usr/lib64/php/modules/pgsql.so
```

and php56w-pdo provides

```
rpm -ql php56w-pdo   
/etc/php-zts.d/pdo.ini
/etc/php-zts.d/pdo_sqlite.ini
/etc/php-zts.d/sqlite3.ini
/etc/php.d/pdo.ini
/etc/php.d/pdo_sqlite.ini
/etc/php.d/sqlite3.ini
/usr/lib64/php-zts/modules/pdo.so
/usr/lib64/php-zts/modules/pdo_sqlite.so
/usr/lib64/php-zts/modules/sqlite3.so
/usr/lib64/php/modules/pdo.so
/usr/lib64/php/modules/pdo_sqlite.so
/usr/lib64/php/modules/sqlite3.so
```

so looks like i am only missing pgsql.so from http://php.net/manual/en/pgsql.installation.php so will look into that

**Comment by centminmod** [comment]
@TooKennySupreme all done missing pgsql.so added https://community.centminmod.com/posts/24040/ in 123.09beta01 branch :)

**Comment by TooKennySupreme** [comment]
Well done !
