### ISSUE TITLE
centmin.sh can't update memcached; script fails at line 663

### ISSUE THREAD

**Issue by OttawaMark** [centminmod/centminmod#52]
After running option 23, then 2 (to update the current version), command line invocation of ./centmin.sh fails with the following error message:
```
patch unexpectedly ends in middle of line
1 out of 1 hunk FAILED -- saving rejects to file memcached.rej
./centmin.sh: line 663: inc/custom_config.inc: No such file or directory
```

What appears to be going on:
- Finding the file inc/custom_config.inc using the relative path fails because the current path has the unexpected value of /etc/init.d
- Related to a failure in lines 207-222 of inc/cpcheck.inc, where the current directory is changed to /etc/init.d

memcached.rej looks like:
```
--- memcached 2015-11-24 00:22:37.512363496 +0000
+++ memcached.new 2015-11-23 23:53:57.166708853 +0000
@@ -26,6 +26,13 @@
 PIDA='/var/run/memcached/memcached1.pid'
 PIDB='/var/run/memcached/memcached2.pid'
 
+# 1.4.25 new slab options
+# https://github.com/memcached/memcached/wiki/ReleaseNotes1425
+MEM_CURVER=$(/usr/local/bin/memcached -V | awk '{print $2}' | head -n1 | sed -e 's|\.|00|g')
+if [[ "$MEM_CURVER" -ge '10040025' ]]; then
+        OPTIONS='-o slab_reassign,slab_automove,lru_crawler,lru_maintainer,maxconns_fast,hash_algorithm=murmur3'
+fi
+
 if [ -f /proc/user_beancounters ]; then
 ulimit -s 256
```

**Comment by OttawaMark** [comment]
memcached -h
memcached 1.4.17

cat /etc/redhat-release
CentOS release 6.7 (Final)

Centmin Mod 1.2.3-eva2000.08

**Comment by centminmod** [comment]
memcached isn't updated automatically from centmin mod code update

You can start fresh with clean centmin mod code only (won't touch your installed software), just updates centmin mod code at `/usr/local/src/centminmod`. See instructions at https://community.centminmod.com/posts/27848/

Then run centmin.sh menu option 10 to update memcached

**Comment by centminmod** [comment]
ah i see what you mean regarding

* Finding the file inc/custom_config.inc using the relative path fails because the current path has the unexpected value of /etc/init.d
* Related to a failure in lines 207-222 of inc/cpcheck.inc, where the current directory is changed to /etc/init.d

**Comment by centminmod** [comment]
@OttawaMark should be fixed in commit at https://github.com/centminmod/centminmod/commit/1993c68c6e3e9a39e4f68edee3c3d622de22b784

**Comment by jeffwidman** [comment]
If fixed in this commit, then shouldn't this issue be closed?

**Comment by centminmod** [comment]
indeed
