### ISSUE TITLE
Addvhost removes all logs of same centmin.sh execution

### ISSUE THREAD

**Issue by saadismail** [centminmod/centminmod#54]
If I execute centmin.sh & add multiple vhost in the same session then it doesn't keep all logs under centminlogs. All old logs of that session are removed & file only have log for the last vhost addition.

**Comment by saadismail** [comment]
Pushed a pull request #55

**Comment by centminmod** [comment]
@saadismail thanks so much for catching that bug. Usually centmin.sh menu options are run once per session but overlooked running them repeatedly. This commit should fix it in centmin mod 123.09beta01 at https://github.com/centminmod/centminmod/commit/52c833a01e2395df11489fb22aa0ff36387a1f04 which will be the next stable release

also may want to look into /usr/bin/nv command http://centminmod.com/nginx_domain_dns_setup.html

```
/usr/bin/nv -d newdomain.com -s y -u MYFTPUSERNAME
```

**Comment by centminmod** [comment]
hmm that commit didn't work as expected so back to drawing board
