### ISSUE TITLE
SSL - Problem with subdomain redirection 

### ISSUE THREAD

**Issue by IndiAsh** [centminmod/centminmod#59]
Hello
I have a small problem and i don't know if its a bug or not.
I have just setup a ssl certificate. (example domain.com)
the certificate is for the domain http://www.domain.com.
I have also a subdomain http://accounts.domain.com
When i visit the http://www.domain.com i have inserted into the conf to redirect to https://www.domain.com.
The subdomain http://accounts.domain.com does not have a redirection or an active ssl certificate.
If i visit first http://www.domain.com and then the http://accounts.domain.com the site http://accounts.domain.com redirect me to https://accounts.domain.com. If i clear the cache and i go first to http://accounts.domain.com then the redirection does do anything (this is what i want).
Is this a bug or a bad configuration of domain conf?

**Comment by centminmod** [comment]
https://community.centminmod.com/posts/37586/ ;)
