### ISSUE TITLE
application/font-woff2

### ISSUE THREAD

**Issue by raciasolvo** [centminmod/centminmod#60]
123.09beta01
'/usr/local/nginx/conf/mime.types' does not have 'application/font-woff2'.
'content-type:application/octet-stream' sets now.

```
# egrep '(eot|ttf|ott|woff|woff2)' /usr/local/nginx/conf/mime.types
    application/font-woff                 woff;
    application/vnd.ms-fontobject         eot;
```

**Comment by centminmod** [comment]
thanks @raciasolvo for heads up

fixed https://github.com/centminmod/centminmod/commit/012417a329b48721e276fb54c7f87c91af2187b4 :)

**Comment by raciasolvo** [comment]
Thank you!
