### ISSUE TITLE
skip mariadb installation 

### ISSUE THREAD

**Issue by tuwid** [centminmod/centminmod#63]
Hi,
i was just experimenting with centmin i really like it but I have a situation where i should skip the mariadb installation part. Is there any way I could skip the mariadb installation part by some tweaking ?

**Comment by centminmod** [comment]
MariaDB install can't be skipped but you can disable MariaDB service for existing installs. This allows re-enabling if needed.

```
service mysql stop
chkconfig mysql off
```

or pre-install, set variable below in manually created /etc/centminmod/custom_config.inc persist config file

`MYSQLSERVICE_DISABLED='y'`

then install centmin mod which will install MariaDB but disable it post initial install.

**Comment by tuwid** [comment]
no workarounds to just skip it ? Point is that I already have percona on that server and I cant switch now as i have a masterless replica setup there. 
Any other ideas i could use ? @centminmod

**Comment by centminmod** [comment]
Centmin Mod is for fresh OS installs only so if you have existing web stack elements like apache, php or percona mysql then i recommend you do not install Centmin Mod as there's no tests for compatibility in the routines to work nicely with other existing web stack software

**Comment by tuwid** [comment]
@centminmod i only have percona there, no web stack and other stuff but percona is under a cluster and wanted to use centmin for the web stack

**Comment by centminmod** [comment]
answered at https://community.centminmod.com/posts/41722/
