### ISSUE TITLE
limited user / git deployment

### ISSUE THREAD

**Issue by tuwid** [centminmod/centminmod#64]
Hi,
i started recently to use centminmod and I really love it. 
On most cases its the perfect solution but I'm facing this situation where I should give access to 2 devs to git pull / composer update on the staging server. 

Whats the best practice for this on centminmod ? Do i just create the two un-priviledged users and put them in the nginx group (as primary) or there is some "best practice" 

I would normally just use jenkins but i cant do that in this situation so any idea is appreciated

**Comment by centminmod** [comment]
thanks for kind words probably best to ask on the forums as other Centmin Mod users might have tips too https://community.centminmod.com
