### ISSUE TITLE
IMAP / POSTFIX mailbox support in the near future ?

### ISSUE THREAD

**Issue by tuwid** [centminmod/centminmod#66]
Hi,
is there any plan to support mailbox and dns management in the future ?

**Comment by centminmod** [comment]
There's no plans to as I don't want to be troubleshooting email deliverability issues for free which have many factors outside of the postfix/imap servers themselves and for reasons outlined at https://centminmod.com/email.html and https://community.centminmod.com/threads/why-you-may-not-want-to-run-your-own-domain-com-email-server.9065/

use 3rd party @domain.com email providers instead https://community.centminmod.com/threads/free-yourdomain-com-email-accounts-alternatives.280/

**Comment by centminmod** [comment]
dns management you can do already via optional NSD dns https://community.centminmod.com/threads/domain-name-dns-setup-on-local-nsd-server.855/ but like email, for reliability, uptime, performance and better efficient local server resource usage,  best to use 3rd party DNS i.e. cloudflare as dns only is free https://community.centminmod.com/threads/cloudflare-dns-only-configuration.6867/

**Comment by tuwid** [comment]
thanks for the info, abundant as always
