### ISSUE TITLE
I can't install Centmin from my IP 163.172.21.88

### ISSUE THREAD

**Issue by webpuntocero** [centminmod/centminmod#69]
Hi, I'm trying to install centminmod on my server with the IP 163.172.%.% , but is impossible download files from GitHub.

Exist some solution for install centmin from other source?

Here the terminal:

Download axel-2.12.tar.gz ...
--2017-04-13 19:03:11--  https://github.com/eribertomota/axel/archive/2.12.tar.g                                                                                        z
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... failed: Connection                                                                                         timed out.
Connecting to github.com (github.com)|192.30.253.112|:443... failed: Connection                                                                                         timed out.
Retrying.

--2017-04-13 19:03:42--  (try: 2)  https://github.com/eribertomota/axel/archive/                                                                                        2.12.tar.gz
Connecting to github.com (github.com)|192.30.253.113|:443... failed: Connection                                                                                         timed out.
Connecting to github.com (github.com)|192.30.253.112|:443... failed: Connection                                                                                         timed out.
Retrying.

**Comment by centminmod** [comment]
@webpuntocero where is your server located geographically and which web host ? could be Github has blocked your ip or location ? Is it working now ?

**Comment by webpuntocero** [comment]
My server is located in france. 

The issue was fixed by GitHub Staff. My IP address was being blocked, and they've removed the block, so now I can to connect.

I've installed Centmin successfully. Thanks !!

**Comment by centminmod** [comment]
Ah great to hear :)
