### ISSUE TITLE
Strange behavior in mariadbinstallfunct() function in inc/mariadb_install.inc

### ISSUE THREAD

**Issue by alexgoussev** [centminmod/centminmod#75]
The mariadbinstallfunct() function in inc/mariadb_install.inc has two main if-statement
line 432: if [[ "$MDB_INSTALL" = [yY] ]]; 
line 562: if [[ "$MDB_YUMREPOINSTALL" = [yY] ]]; then
I think second 'if' must be 'elif' to prevent installation via yum repo if both MDB_YUMREPOINSTALL and MDB_INSTALL set to 'y'.

**Comment by centminmod** [comment]
thanks @alexgoussev  i changed line 562 to

```
if [[ "$MDB_YUMREPOINSTALL" = [yY] && "$MDB_INSTALL" = [nN] ]]; then
```

to prevent accidental setting of  both MDB_YUMREPOINSTALL and MDB_INSTALL to 'y'.
