### ISSUE TITLE
ARCH_OVERRIDE is used but not defined in centmin.sh, line 655

### ISSUE THREAD

**Issue by alexgoussev** [centminmod/centminmod#76]
line 655 is
if [ "${ARCH_OVERRIDE}" != '' ]
Bit ARCH_OVERRIDE is not defined anywhere above that.
It is just mentioned in commented lines 844-855 below.

The same is in tools/nginxupdate.sh file, line 362.

**Comment by centminmod** [comment]
thanks @alexgoussev seems this boo boo dates back 3yrs ago https://github.com/centminmod/centminmod/blame/123.09beta01/centmin.sh#L655 :)

related to https://github.com/centminmod/centminmod/blob/123.09beta01/readme.txt#L33-L35
