### ISSUE TITLE
Maybe bug in inc/php_configure.inc, line 654

### ISSUE THREAD

**Issue by alexgoussev** [centminmod/centminmod#79]
line 654: 
if [[ "$MDB_INSTALL" == [yY] || "$MYSQL_INSTALL" == [yY] ]]; then

Each part of the if/else-statement contains the same code.

**Comment by centminmod** [comment]
@alexgoussev indeed it does now can't trace back the changes as it was once different for some reason that escapes me now :)

oh i think it's for compiling php without mysql/mysqlnd support when MDB_INSTALL='n' or MYSQL_INSTALL='n' though no one does that and i generally no longer recommend installing them set to no.

**Comment by centminmod** [comment]
whoops my mistake it was correct in the first place as centmin.sh defaults to = n for

```
MDB_INSTALL='n'               # Install via RPM MariaDB MySQL Server replacement (Not recommended for VPS with less than 256MB RAM!)
MYSQL_INSTALL='n'            # Install official Oracle MySQL Server (MariaDB alternative recommended)
```

1st was old manual rpm install and 2nd was official oracle mysql which both are disabled so the else statement is for the default MariaDB official yum repo installs.
