### ISSUE TITLE
Sticky Module & Centminmod Nginx 1.13.0

### ISSUE THREAD

**Issue by duy13** [centminmod/centminmod#90]
```
--------------------------------------------------------
Check Nginx Version:
--------------------------------------------------------
which: no nginx in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
can not find nginx binary.. install failed
```

Install **nginx-sticky-module-ng** module in **123.09beta01** failed

```
yum -y install git wget nano bc unzip
cd /usr/local/src
branchname=123.09beta01
git clone -b ${branchname} --depth=1 https://github.com/centminmod/centminmod.git centminmod
cd centminmod
```

Edit **centmin.sh**:

```
NGINX_STICKY='y'
NGINX_STICKYVER='master'
```

May be Nginx 1.13.0 does not compatible with sticky-module?

**Comment by centminmod** [comment]
yeah last time i checked it was broken https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng/issues/17/nginx-19-with-stream-module-conflict

**Comment by duy13** [comment]
Thanks, so if we do not compile --with-stream is it work?

**Comment by centminmod** [comment]
try and see though https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng/issues/26/not-compile-nginx-1112 suggests it won't work
