### ISSUE TITLE
How to change the MariaDB default mirror?

### ISSUE THREAD

**Issue by jellday** [centminmod/centminmod#94]
I encounter connection time out problem when fresh install centminmod during MariaDB yum installation and through centmin.sh option 11.
The MariaDB thus is not installed.
The problem causing that is the VPS is in China, and have poor connection of the default download link. But MariaDB does have mirrors in China.
How do I do to replace the default mirror with the China one?
And now since my MDB is not installed, which option I should choose under centmin.sh option 11?

And the last one, I cannot get in touch with you, eva2000, your site's recapcha is not loading in China, and if I use VPN, it will turn down automatically.
Please help.

**Comment by centminmod** [comment]
> And the last one, I cannot get in touch with you, eva2000, your site's recapcha is not loading in China, and if I use VPN, it will turn down automatically.

Sorry to hear, unfortunately such problems with China connectivity are out of my control. What do you mean VPN usage will turn down automatically ?

As to MariaDB mirror changing, not entirely sure would probably need to contact MariaDB themselves and see what options are available as I am sure you're not the only person having issues with China connectivity.

**Comment by centminmod** [comment]
Also to troubleshoot initial install issues, having access to the initial install log would be useful.

## Troubleshooting Initial Install

To troubleshoot initial installation, you need to check the initial install log at /root/centminlogs and instructions under Sharing logs and errors heading for using Pastebin.com or gist.github.com to share a sanitised version of the contents of the initial install log. 

Example list /root/centminlogs files in date ascending order and grep for install.log

```
ls -lahrt /root/centminlogs | grep install.log
```

example output returns install log at /root/centminlogs/centminmod_1.2.3-eva2000.09.001_111016-112321_install.log

```
ls -lahrt /root/centminlogs | grep install.log
-rw-r--r--  1 root root 2.2M Oct 11 01:40 centminmod_1.2.3-eva2000.09.001_111016-112321_install.log
```

in SSH use cat to ouput contents of /root/centminlogs/centminmod_1.2.3-eva2000.09.001_111016-112321_install.log. Clear your SSH client window/buffer so only output is the contents of the file

```
cat /root/centminlogs/centminmod_1.2.3-eva2000.09.001_111016-112321_install.log
```

Then copy and paste into Pastebin.com or Gists entry. If your SSH window scroll buffer isn't that large to get the whole contents of the install log, you can download file manually and copy and paste contents. But makes sure it's sanitised version of the contents of the initial install log as outlined at [How to troubleshoot Centmin Mod initial install issues](https://community.centminmod.com/threads/how-to-troubleshoot-centmin-mod-initial-install-issues.102/)

**Comment by jellday** [comment]
Thank you for your detailed help!!!
yum list MariaDB-client MariaDB-common MariaDB-compat MariaDB-devel MariaDB-server MariaDB-shared
Output:
`[21:41][root@jdcloud.xxx.net ~]# yum list MariaDB-client MariaDB-common MariaDB-compat MariaDB-devel MariaDB-server MariaDB-shared
Loaded plugins: fastestmirror, priorities, security
Repository base is listed more than once in the configuration
Repository updates is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository centosplus is listed more than once in the configuration
Repository contrib is listed more than once in the configuration
Error: File contains no section headers.
file: file:///etc/yum.repos.d/centalt.repo, line: 1
'exclude=mariadb*\n'`

System Uptime: 	up 2 days, 10:55,
 MySQL Server Started 	not running
 MySQL Uptime: 		not running
 MySQL Uptime (secs): 	not running
 Server Type: 		kvm
 CentOS Version: 	6.9
 Centmin Mod: 		1.2.3-eva2000.09.005
 Nginx PageSpeed: 	OFF
 Nginx Version: 	1.13.2
 PHP-FPM Version: 	5.6.30
 MariaDB Version: 	
 CSF Firewall: 		v10.14
 Memcached Server: 	1.4.38
 NSD Version: 		 - 
 Siege Version: 	4.0.2
 Maldet Version: 	not installed
 ClamAV Version: 	not installed
 ElasticSearch: 	not installed

You see, MySQL is not installed and running. I tried the centmin.sh submenu 1 -- "1). MariaDB 5.2.x Branch Upgrade Only" installed successfully, but if I type mysql, I get access denied, even after resetting root passoword.

CentOS 6 64bit

curl -s ipinfo.io/geo
{
  "ip": "113.209.77.74",
  "city": "Beijing",
  "region": "Beijing",
  "country": "CN",
  "loc": "39.9289,116.3883"}

My Host is JCloud.com (provider is one of the biggest B2C shops in China), one core, 2G, 30GB HD.

The install.log is too big to paste. I put it in a cloud drive: http://pan.baidu.com/s/1eRBLc1W pwd: faj7

The last one, "if I use VPN, it will turn down automatically", I mean since the capcha is not loading properly, I have to use a VPN or a proxy to browse that page, and when I click submit, it says, cannot submit, because of robot action etc... For that reason, I cannot reset or register a new account in your forum. Can you just reset my jellday account's pass and send it to my jellday at hotmail.com mailbox? Also, username "JR Day" is also my account.

**Comment by centminmod** [comment]
hostmail and 126.com are banned email providers on my forum right now

what happens when you remove backup and then remove `/etc/yum.repos.d/centalt.repo` file and run `yum clean all` and try again

```
yum list MariaDB-client MariaDB-common MariaDB-compat MariaDB-devel MariaDB-server MariaDB-shared
```

**Comment by jellday** [comment]
# yum list MariaDB-client MariaDB-common MariaDB-compat MariaDB-devel MariaDB-server MariaDB-shared
Loaded plugins: fastestmirror, priorities, security
Repository base is listed more than once in the configuration
Repository updates is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository centosplus is listed more than once in the configuration
Repository contrib is listed more than once in the configuration
Determining fastest mirrors
epel/metalink                                                                                                                                       | 5.4 kB     00:00     
 * epel: mirrors.ustc.edu.cn
 * rpmforge: mirrors.neusoft.edu.cn
base                                                                                                                                                | 3.7 kB     00:00     
base/primary_db                                                                                                                                     | 4.7 MB     00:00     
http://mirror.centos.org/centos/6/sclo/x86_64/rh/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "Failed to connect to 2605:9000:401:102::2: Network is unreachable"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: centos-sclo-rh. Please verify its path and try again

I see why MariaDB is not successful after failing the initial installation. 

If 126/hotmail/yahoo is banned, can you reset my account and make its email pointed to "j dot dai at 139 dot com" OR "j dot dai at aliyun dot com".

**Comment by centminmod** [comment]
"Failed to connect to 2605:9000:401:102::2: Network is unreachable

Looks like IPv6 networking isn't working on your server.  You can try disabling IPv6 on your server using same method of /etc/sysctl.conf edit outlined at https://community.centminmod.com/threads/troubleshoot-slow-ssh-logins.12124/ adding to /etc/sysctl.conf

```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
```
then run

```
sysctl -p
```
then try again

```
yum clean all
yum list MariaDB-client MariaDB-common MariaDB-compat MariaDB-devel MariaDB-server MariaDB-shared
```

also i set your email for jellday account to aliyum email, you can edit your above post to remove the emails for privacy.

**Comment by jellday** [comment]
I found a solution, replace the default configuration section:
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/10.1/centos7-amd64
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1

with one of the mirror url in China
[mariadb]
name = MariaDB
baseurl = https://mirrors.tuna.tsinghua.edu.cn/mariadb/yum/10.1/centos7-amd64
gpgkey = https://mirrors.tuna.tsinghua.edu.cn/mariadb/yum//RPM-GPG-KEY-MariaDB
gpgcheck = 1

I found the same parts in mariadb_install.inc file under inc directory. Is that the only file I need to modify for initial installation? The default version for MariaDB is 10.0 or 10.1 in the latest version of centminmod? Thank you and I feel I am getting closer to the answer.

**Comment by jellday** [comment]
The output for yum list...
yum list MariaDB-client MariaDB-common MariaDB-compat MariaDB-devel MariaDB-server MariaDB-shared
Loaded plugins: fastestmirror, priorities, security
Repository base is listed more than once in the configuration
Repository updates is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository centosplus is listed more than once in the configuration
Repository contrib is listed more than once in the configuration
Determining fastest mirrors
epel/metalink                                                                                                                                       | 5.4 kB     00:00     
 * epel: mirrors.neusoft.edu.cn
 * rpmforge: mirrors.neusoft.edu.cn
base                                                                                                                                                | 3.7 kB     00:00     
base/primary_db                                                                                                                                     | 4.7 MB     00:00     
centos-sclo-rh                                                                                                                                      | 2.9 kB     00:00     
centos-sclo-rh/primary_db                                                                                                                           | 2.5 MB     00:04     
centos-sclo-sclo                                                                                                                                    | 2.9 kB     00:00     
centos-sclo-sclo/primary_db                                                                                                                         | 116 kB     00:00     
epel                                                                                                                                                | 4.3 kB     00:00     
epel/primary_db                                                                                                                                     | 5.9 MB     00:08     
extras                                                                                                                                              | 3.4 kB     00:00     
extras/primary_db                                                                                                                                   |  29 kB     00:00     
mariadb                                                                                                                                             | 2.9 kB     00:00     
mariadb/primary_db                                                                                                                                  |  20 kB     00:00     
rpmforge                                                                                                                                            | 1.9 kB     00:00     
rpmforge/primary_db                                                                                                                                 | 2.7 MB     00:03     
updates                                                                                                                                             | 3.4 kB     00:00     
updates/primary_db                                                                                                                                  | 2.0 MB     00:00     
varnish-4.1                                                                                                                                         |  951 B     00:00     
varnish-4.1/primary                                                                                                                                 |  11 kB     00:00     
varnish-4.1                                                                                                                                                          37/37
1501 packages excluded due to repository priority protections
Installed Packages
MariaDB-shared.x86_64                                                               5.2.14-122.el5                                                                installed
Available Packages
MariaDB-client.x86_64                                                               5.5.56-1.el6                                                                  mariadb  
MariaDB-common.x86_64                                                               5.5.56-1.el6                                                                  mariadb  
MariaDB-compat.x86_64                                                               5.5.56-1.el6                                                                  mariadb  
MariaDB-devel.x86_64                                                                5.5.56-1.el6                                                                  mariadb  
MariaDB-server.x86_64                                                               5.5.56-1.el6                                                                  mariadb  
MariaDB-shared.x86_64                                                               5.5.56-1.el6                                                                  mariadb 

It looks like selecting the menu "1). MariaDB 5.2.x Branch Upgrade Only" did install me a MariaDB 5.2.

**Comment by centminmod** [comment]
> I found the same parts in mariadb_install.inc file under inc directory. Is that the only file I need to modify for initial installation? The default version for MariaDB is 10.0 or 10.1 in the latest version of centminmod? Thank you and I feel I am getting closer to the answer.

yes that was the solution i was thinking of eventually 

your  curl ipinfo.io result is what i was thinking of basing the detection on so if country = CN, use a different base mirror

```
curl -s ipinfo.io/geo
{
"ip": "113.209.77.74",
"city": "Beijing",
"region": "Beijing",
"country": "CN",
"loc": "39.9289,116.3883"}
```

**Comment by centminmod** [comment]
try updated 123.09beta01 beta now with China server auto detection https://github.com/centminmod/centminmod/commit/408b1c6cebe1a0ffa3eeda2712af0829afae2d2a :)

**Comment by jellday** [comment]
Yes, replace the mirror and problem solved

**Comment by centminmod** [comment]
Great to hear. FYI, usually mariadb yum mirror system should of pointed you to China mirrors automatically but seems they didn't for you.
