### ISSUE TITLE
yum release version not found.

### ISSUE THREAD

**Issue by johnbritto1** [centminmod/centminmod#99]
Hello,

I am getting the following error while doing yum preflight check.

> *************************************************
> * CentOS 7.x detected installing EPEL Repo
> *************************************************
> Error: rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm not found !!! Downloading now......
> failed: Connection timed out.
> failed: Connection timed out.
> failed: Connection timed out.
> Error: rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm download failed.
>  
> ----------------------------------------------------------------------------------
> check Centmin Mod log for details at /root/centminlogs/
> Aborting script...
> ----------------------------------------------------------------------------------
> Error: percona-release-0.1-3.noarch.rpm not found !!! Downloading now......
> https://www.percona.com/redir/downloads/percona-release/redhat/latest/percona-release-0.1-3.noarch.rpm:
> 2017-08-30 12:56:50 ERROR 404: Not Found.
> Error: percona-release-0.1-3.noarch.rpm download failed.

It turns out to be that the inc/downloadlinks.inc file wasn't updated.
Could you please check it once because i could be wrong. 
eg: CENTOSSEVENPERCONALRELEASEFILE="percona-release-0.1-3.noarch.rpm" doesn't exist.
CENTOSSEVENEPELFILE="epel-release-7-2.noarch.rpm" doesn't exist.
CENTOSSEVENRPMFORGE="http://pkgs.repoforge.org/rpmforge-release/${CENTOSSEVENRPMFORGEFILE}" the website is down. any mirrior would be great.

**Comment by centminmod** [comment]
thanks for the heads up should be fixed in 123.09beta01 branch https://github.com/centminmod/centminmod/commit/ee39f0e5056784e8d84b7f0d0acdd319b15abbf1 :)
